image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  BASE_ID: "$CI_REGISTRY_IMAGE/base:$CI_COMMIT_REF_SLUG"
  TEST_ID: "$CI_REGISTRY_IMAGE/test:$CI_COMMIT_REF_SLUG"

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

pages:
  stage: build
  script:
    - apk add python3 py3-pip
    - pip install -r requirements.txt
    - make -C doc html
    - mv doc/_build/html/ public/
  artifacts:
    paths:
      - public

build:
  stage: build
  script:
    - docker pull $BASE_ID || true
    - docker build --cache-from $BASE_ID --target base -t $BASE_ID .
    - docker push $BASE_ID
  only:
    - master
    - tags
    - dev

.test_template: &test_template
  stage: test
  script:
    - docker pull $TEST_ID || true
    - docker build --cache-from $TEST_ID --target test -t $TEST_ID .
    - docker push $TEST_ID
    - docker run --name cat-test $RUN_ARGS $TEST_ID
  after_script:
    - docker cp cat-test:/app/test-results.json test-results.json
    - docker cp cat-test:/app/test-results-py2.xml test-results-py2.xml
    - docker cp cat-test:/app/test-results-py3.xml test-results-py3.xml
  artifacts:
    when: always
    paths:
      - test-results.json
      - test-results-*.xml
    reports:
      junit: test-results-*.xml

test_master:
  <<: *test_template
  variables:
    RUN_ARGS: "--env RUN_ARGS='--slow'"
  only:
    - master

test:
  <<: *test_template
  variables:
    RUN_ARGS: ""
  only:
    - dev
    - tags

