image: docker:latest

services:
  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build:
  stage: build
  script:
    - docker build --pull --target base -t "$CI_REGISTRY_IMAGE-base:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE-base:$CI_COMMIT_REF_SLUG"

test:
  stage: test
  script:
    - docker build --pull --target test -t "$CI_REGISTRY_IMAGE-test:$CI_COMMIT_REF_SLUG" .
    - docker run "$CI_REGISTRY_IMAGE-test:$CI_COMMIT_REF_SLUG" .

doc:
  stage: doc
  script:
    - docker build --pull --target doc -t "$CI_REGISTRY_IMAGE-doc:$CI_COMMIT_REF_SLUG" .
    - docker run "$CI_REGISTRY_IMAGE-doc:$CI_COMMIT_REF_SLUG" .
