image: docker:latest

services:
  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build:
  stage: build
  script:
    - docker build --target base -t "$CI_REGISTRY_IMAGE-base:$CI_COMMIT_REF_SLUG" .
    # - docker push "$CI_REGISTRY_IMAGE-base:$CI_COMMIT_REF_SLUG"

test:
  stage: test
  script:
    - docker build --target test -t "$CI_REGISTRY_IMAGE-test:$CI_COMMIT_REF_SLUG" .
    - docker run --name cat-test "$CI_REGISTRY_IMAGE-test:$CI_COMMIT_REF_SLUG"
    - docker cp cat-test:/app/test-results.json test-results.json
    - docker cp cat-test:/app/test-results-py2.xml test-results-py2.xml
    - docker cp cat-test:/app/test-results-py3.xml test-results-py3.xml
  artifacts:
    reports:
      junit: test-results-py3.xml
